In [1]:
class MeraLR:
    def __init__(self):
        self.m = None
        self.b = None
    def fit(self,x_train,y_train):
        num=0
        den=0
        
        for i in range(x_train.shape[0]):
            num=num+((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den=den+((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))
            
        self.m=num/den
        self.b=(y_train.mean() - (self.m*(x_train.mean())))
        print(self.m)
        print(self.b)
        
            
    def predict(self,x_test):
        for i in range(x_test.shape[0]):
            y_pred=(self.m*(x_test[i])+self.b)
            print(y_pred)
        
       
    

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
import io
%cd "D:\Amazon movie\slr"

D:\Amazon movie\slr


In [4]:
df=pd.read_csv("SLR.csv")

In [5]:
df.head()

X          Y
0  20.000000  88.599998
1  16.000000  71.599998
2  19.799999  93.300003
3  18.400000  84.300003
4  17.100000  80.599998

In [6]:
X=df.iloc[:,0].values

In [7]:
Y=df.iloc[:,1].values

In [8]:
X

array([20.        , 16.        , 19.79999924, 18.39999962, 17.10000038,
       15.5       , 14.69999981, 17.10000038, 15.39999962, 16.20000076,
       15.        , 17.20000076, 16.        , 17.        , 14.39999962])

In [9]:
Y

array([88.59999847, 71.59999847, 93.30000305, 84.30000305, 80.59999847,
       75.19999695, 69.69999695, 82.        , 69.40000153, 83.30000305,
       79.59999847, 82.59999847, 80.59999847, 83.5       , 76.30000305])

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [12]:
LR=MeraLR()

In [13]:
LR.fit(x_train,y_train) #value of m(slope) and b(intercept)

3.6167472795003386
19.647569798033942


In [14]:
LR.predict(x_test) #predict

78.23887847466736
81.8556257541677
91.98251538804071


In [15]:
y_test #actual

array([83.30000305, 82.59999847, 88.59999847])

In [16]:
#lets try same data with scikit learn class
from sklearn.linear_model import LinearRegression

In [17]:
lr=LinearRegression()

In [18]:
X_train=x_train.reshape(-1,1)
Y_train=y_train.reshape(-1,1)

In [19]:
model1=lr.fit(X_train,Y_train)

In [20]:
model1.coef_

array([[3.61674728]])

In [21]:
model1.intercept_

array([19.6475698])

In [22]:
y_pred1=model1.predict(x_test.reshape(-1,1))

In [23]:
y_pred1

array([[78.23887847],
       [81.85562575],
       [91.98251539]])

In [24]:
# both models m and b value found simmilar hence SKlearn Linear regression also following OLS(Ordinary Least Square)